export const SELECCCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE'
export const SELECCCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_PRODUCTOS'
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL'